common: &common
  adapter: postgresql
  username: postgres
  password: 8Wimbledon9!
  
development:
  <<: *common
  database: nationsservice_development
  
test:
  <<: *common
  database: nationsservice_test
  
production:
  <<: *common
  database: nationsservice_production
